- hosts: all
  become: true
  tasks:
    - name: Install Frappe Docker inside the site user home directory
      ansible.builtin.git:
        repo: https://github.com/frappe/frappe_docker.git
        dest: "/home/{{ site_name }}/"
        version: main
        update: yes

